export const GET_PRODUCTS_REQUEST_WOMEN = "GET_PRODUCTS_REQUEST_WOMEN";
export const GET_PRODUCTS_SUCCESS_WOMEN = "GET_PRODUCTS_SUCCESS_WOMEN";
export const GET_PRODUCTS_FAILURE_WOMEN = "GET_PRODUCTS_FAILURE_WOMEN";
