export const GET_USER_WISHLIST_PRODUCTS_REQUEST =
  "GET_USER_WISHLIST_PRODUCTS_REQUEST";
export const GET_USER_WISHLIST_PRODUCTS_SUCCESS =
  "GET_USER_WISHLIST_PRODUCTS_SUCCESS";
export const GET_USER_WISHLIST_PRODUCTS_FAILURE =
  "GET_USER_WISHLIST_PRODUCTS_FAILURE";

export const ADD_USER_WISHLIST_PRODUCTS_REQUEST =
  "ADD_USER_WISHLIST_PRODUCTS_REQUEST";
export const ADD_USER_WISHLIST_PRODUCTS_SUCCESS =
  "ADD_USER_WISHLIST_PRODUCTS_SUCCESS";
export const ADD_USER_WISHLIST_PRODUCTS_FAILURE =
  "ADD_USER_WISHLIST_PRODUCTS_FAILURE";

export const DELETE_USER_WISHLIST_PRODUCTS_REQUEST =
  "DELETE_USER_WISHLIST_PRODUCTS_REQUEST";
export const DELETE_USER_WISHLIST_PRODUCTS_SUCCESS =
  "DELETE_USER_WISHLIST_PRODUCTS_SUCCESS";
export const DELETE_USER_WISHLIST_PRODUCTS_FAILURE =
  "DELETE_USER_WISHLIST_PRODUCTS_FAILURE";
