export const GET_PRODUCTS_REQUEST_MEN = "GET_PRODUCTS_REQUEST_MEN";
export const GET_PRODUCTS_SUCCESS_MEN = "GET_PRODUCTS_SUCCESS_MEN";
export const GET_PRODUCTS_FAILURE_MEN = "GET_PRODUCTS_FAILURE_MEN";
