export const GET_USER_PRODUCTS_REQUEST = "GET_USER_PRODUCTS_REQUEST";
export const GET_USER_PRODUCTS_SUCCESS = "GET_USER_PRODUCTS_SUCCESS";
export const GET_USER_PRODUCTS_FAILURE = "GET_USER_PRODUCTS_FAILURE";

export const ADD_USER_PRODUCTS_REQUEST = "ADD_USER_PRODUCTS_REQUEST";
export const ADD_USER_PRODUCTS_SUCCESS = "ADD_USER_PRODUCTS_SUCCESS";
export const ADD_USER_PRODUCTS_FAILURE = "ADD_USER_PRODUCTS_FAILURE";
