export const GET_PRODUCTS_REQUEST_KIDS = "GET_PRODUCTS_REQUEST_KIDS";
export const GET_PRODUCTS_SUCCESS_KIDS = "GET_PRODUCTS_SUCCESS_KIDS";
export const GET_PRODUCTS_FAILURE_KIDS = "GET_PRODUCTS_FAILURE_KIDS";
