export const SIGNUP_REQUEST = "SIGNUP_REQUEST";
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";

export const CHECK_REGISTER_USER_REQUEST = "CHECK_REGISTER_USER_REQUEST";
export const CHECK_REGISTER_USER_SUCCESS = "CHECK_REGISTER_USER_SUCCESS";
export const CHECK_REGISTER_USER_ERROR = "CHECK_REGISTER_USER_ERROR";

export const LOGOUT = "LOGOUT";
