export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILURE = "GET_PRODUCTS_FAILURE";

export const UPDATE_TASKS_REQUEST = "UPDATE_TASKS_REQUEST";
export const UPDATE_TASKS_SUCCESS = "UPDATE_TASKS_SUCCESS";
export const UPDATE_TASKS_FAILURE = "UPDATE_TASKS_FAILURE";

export const ADD_TASKS_REQUEST = "ADD_TASKS_REQUEST";
export const ADD_TASKS_SUCCESS = "ADD_TASKS_SUCCESS";
export const ADD_TASKS_FAILURE = "ADD_TASKS_FAILURE";

export const DELETE_TASKS_REQUEST = "DELETE_TASKS_REQUEST";
export const DELETE_TASKS_SUCCESS = "DELETE_TASKS_SUCCESS";
export const DELETE_TASKS_FAILURE = "DELETE_TASKS_FAILURE";

export const UPDATE_SUBTASKS_STATUS_REQUEST = "UPDATE_SUBTASKS_STATUS_REQUEST";
export const UPDATE_SUBTASKS_STATUS_SUCCESS = "UPDATE_SUBTASKS_STATUS_SUCCESS";
export const UPDATE_SUBTASKS_STATUS_FAILURE = "UPDATE_SUBTASKS_STATUS_FAILURE";
